Age: 30
Goods_Number: qa123445678
Goods_Size: 100
Mysql_DbName: ""
Mysql_Host: 127.0.0.1:3306
Mysql_IgnoreLog: false
Mysql_MaxIdleConn: 5
Mysql_MaxOpenConn: 10
Mysql_Password: ""
Mysql_User: root
Prom_Addr: 1.2.3.4
Name: xiaoxlm
Redis_DB: 0
Redis_Host: 127.0.0.1:6379
Redis_Password: ""
Redis_PoolSize: 5
Redis_Timeout: 0
Redis_Username: ""
Server_HttpPort: 0
Server_LogLevel: ""
Server_RunMode: ""
