Age: 30
Goods_Number: qa123445678
Goods_Size: 100
Mysql_DbName: liming
Mysql_Host: 127.0.0.1:3306
Mysql_IgnoreLog: false
Mysql_MaxIdleConn: 5
Mysql_MaxOpenConn: 10
Mysql_Password: uWXf87plmQGz8zMM
Mysql_User: root
Name: xiaoxlm
Server_HttpPort: 80
Server_LogLevel: DEBUG
Server_RunMode: ""
